---
# file: tasks/section_5.yml
# ======================================================================
# Section 5
# Access, Authentication and Authorization
# ======================================================================

# ----------------------------------------------------------------------
# Section 5.1
# Configure cron
# ----------------------------------------------------------------------

# ----------------------------------------------------------------------
# Section 5.2
# SSH Server Configuration
# ----------------------------------------------------------------------

# ----------------------------------------------------------------------
# Section 5.3
# Configure PAM
# ----------------------------------------------------------------------

# ----------------------------------------------------------------------
# Section 5.4
# User Accounts and Environment
# ----------------------------------------------------------------------

# ----------------------------------------------------------------------
# Section 5.5
# root login
# ----------------------------------------------------------------------

# ----------------------------------------------------------------------
# Section 5.6
# su access
# ----------------------------------------------------------------------

# End -- Section 5
# ======================================================================
