---
# file: tasks/section_5.yml
# ======================================================================
# Section 5
# Access, Authentication and Authorization
# ======================================================================

# ----------------------------------------------------------------------
# Section 5.1
# Configure cron
# ----------------------------------------------------------------------

- name: "SCORED | 5.1.1 | PATCH | Ensure cron daemon is enabled"
  service:
    name: "{{ cron_service[ansible_os_family] }}"
    enabled: yes
  when:
    - debian9cis_rule_5_1_1
  tags:
    - level1
    - scored
    - patch
    - services
    - cron
    - rule_5.1.1

- name: "SCORED | 5.1.2 | PATCH | Ensure permissions on /etc/crontab are configured"
  file:
    path: /etc/crontab
    owner: root
    group: root
    mode: "0600"
  when:
    - debian9cis_rule_5_1_2
  tags:
    - level1
    - scored
    - patch
    - cron
    - rule_5.1.2

- name: "SCORED | 5.1.3 | PATCH | Ensure permissions on /etc/cron.hourly are configured"
  file:
    path: /etc/cron.hourly
    state: directory
    owner: root
    group: root
    mode: "0700"
  when:
    - debian9cis_rule_5_1_3
  tags:
    - level1
    - scored
    - patch
    - cron
    - rule_5.1.3

- name: "SCORED | 5.1.4 | PATCH | Ensure permissions on /etc/cron.daily are configured"
  file:
    path: /etc/cron.daily
    state: directory
    owner: root
    group: root
    mode: "0700"
  when:
    - debian9cis_rule_5_1_4
  tags:
    - level1
    - scored
    - patch
    - cron
    - rule_5.1.4

- name: "SCORED | 5.1.5 | PATCH | Ensure permissions on /etc/cron.weekly are configured"
  file:
    path: /etc/cron.weekly
    state: directory
    owner: root
    group: root
    mode: "0700"
  when:
    - debian9cis_rule_5_1_5
  tags:
    - level1
    - scored
    - patch
    - cron
    - rule_5.1.5

- name: "SCORED | 5.1.6 | PATCH | Ensure permissions on /etc/cron.monthly are configured"
  file:
    path: /etc/cron.monthly
    state: directory
    owner: root
    group: root
    mode: "0700"
  when:
    - debian9cis_rule_5_1_6
  tags:
    - level1
    - scored
    - patch
    - cron
    - rule_5.1.6

- name: "SCORED | 5.1.7 | PATCH | Ensure permissions on /etc/cron.d are configured"
  file:
    path: /etc/cron.d
    state: directory
    owner: root
    group: root
    mode: "0700"
  when:
    - debian9cis_rule_5_1_7
  tags:
    - level1
    - scored
    - patch
    - cron
    - rule_5.1.7

- name: "SCORED | 5.1.8 | PATCH | Ensure at/cron is restricted to authorized users"
  block:
    - file:
        path: /etc/at.deny
        state: absent
    - file:
        path: /etc/at.allow
        state: touch
        owner: root
        group: root
        mode: "0600"
    - file:
        path: /etc/cron.deny
        state: absent
    - file:
        path: /etc/cron.allow
        state: touch
        owner: root
        group: root
        mode: "0600"
  when:
    - debian9cis_rule_5_1_8
  tags:
    - level1
    - scored
    - patch
    - cron
    - rule_5.1.8

# ----------------------------------------------------------------------
# Section 5.2
# SSH Server Configuration
# ----------------------------------------------------------------------

- name: "SCORED | 5.2.1 | PATCH | Ensure permissions on /etc/ssh/sshd_config are configured"
  file:
    path: /etc/ssh/sshd_config
    state: file
    owner: root
    group: root
    mode: "0600"
  when:
    - debian9cis_rule_5_2_1
  tags:
    - level1
    - scored
    - patch
    - sshd
    - rule_5.2.1

- name: "SCORED | 5.2.2 | PATCH | Ensure permissions on SSH private host key files are configured"
  block:
    - find:
        paths: /etc/ssh
        patterns: "ssh_host_*_key"
        file_type: file
      register: ssh_priv_host_keys
    - file:
        path: "{{ item.path }}"
        state: file
        owner: root
        group: root
        mode: "0600"
      with_items: "{{ ssh_priv_host_keys.files }}"
      when:
        - ssh_priv_host_keys is defined
        - ssh_priv_host_keys.matched > 0
  when:
    - debian9cis_rule_5_2_2
  tags:
    - level1
    - scored
    - patch
    - sshd
    - rule_5.2.2

- name: "SCORED | 5.2.3 | PATCH | Ensure permissions on SSH public host key files are configured"
  block:
    - find:
        paths: /etc/ssh
        patterns: "ssh_host_*_key.pub"
        file_type: file
      register: ssh_pub_host_keys
    - file:
        path: "{{ item.path }}"
        state: file
        owner: root
        group: root
        mode: "0644"
      with_items: "{{ ssh_pub_host_keys.files }}"
      when:
        - ssh_pub_host_keys is defined
        - ssh_pub_host_keys.matched > 0
  when:
    - debian9cis_rule_5_2_3
  tags:
    - level1
    - scored
    - patch
    - sshd
    - rule_5.2.3

- name: "SCORED | 5.2.4 | PATCH | Ensure SSH Protocol is set to 2"
  lineinfile:
    state: present
    path: /etc/ssh/sshd_config
    regexp: '^(#)?Protocol '
    line: 'Protocol 2'
  notify: restart sshd
  when:
    - debian9cis_rule_5_2_4
  tags:
    - level1
    - scored
    - patch
    - sshd
    - rule_5.2.4

- name: "SCORED | 5.2.5 | PATCH | Ensure SSH LogLevel is appropriate"
  lineinfile:
    state: present
    path: /etc/ssh/sshd_config
    regexp: '^(#)?LogLevel '
    line: 'LogLevel INFO'
  notify: restart sshd
  when:
    - debian9cis_rule_5_2_5
  tags:
    - level1
    - scored
    - patch
    - sshd
    - rule_5.2.5

- name: "SCORED | 5.2.6 | PATCH | Ensure SSH X11 forwarding is disabled"
  lineinfile:
    state: present
    path: /etc/ssh/sshd_config
    regexp: '^(#)?X11Forwarding '
    line: 'X11Forwarding no'
  notify: restart sshd
  when:
    - debian9cis_rule_5_2_6
  tags:
    - level1
    - scored
    - patch
    - sshd
    - rule_5.2.6

- name: "SCORED | 5.2.7 | PATCH | Ensure SSH MaxAuthTries is set to 4 or less"
  lineinfile:
    state: present
    path: /etc/ssh/sshd_config
    regexp: '^(#)?MaxAuthTries '
    line: 'MaxAuthTries 4'
  notify: restart sshd
  when:
    - debian9cis_rule_5_2_7
  tags:
    - level1
    - scored
    - patch
    - sshd
    - rule_5.2.7

- name: "SCORED | 5.2.8 | PATCH | Ensure SSH IgnoreRhosts is enabled"
  lineinfile:
    state: present
    path: /etc/ssh/sshd_config
    regexp: '^(#)?IgnoreRhosts '
    line: 'IgnoreRhosts yes'
  notify: restart sshd
  when:
    - debian9cis_rule_5_2_8
  tags:
    - level1
    - scored
    - patch
    - sshd
    - rule_5.2.8

- name: "SCORED | 5.2.9 | PATCH | Ensure SSH HostbasedAuthentication is disabled"
  lineinfile:
    state: present
    path: /etc/ssh/sshd_config
    regexp: '^(#)?HostbasedAuthentication '
    line: 'HostbasedAuthentication no'
  notify: restart sshd
  when:
    - debian9cis_rule_5_2_9
  tags:
    - level1
    - scored
    - patch
    - sshd
    - rule_5.2.9

- name: "SCORED | 5.2.10 | PATCH | Ensure SSH root login is disabled"
  lineinfile:
    state: present
    path: /etc/ssh/sshd_config
    regexp: '^(#)?PermitRootLogin '
    line: 'PermitRootLogin no'
  notify: restart sshd
  when:
    - debian9cis_rule_5_2_10
  tags:
    - level1
    - scored
    - patch
    - sshd
    - rule_5.2.10

- name: "SCORED | 5.2.11 | PATCH | Ensure SSH PermitEmptyPasswords is disabled"
  lineinfile:
    state: present
    path: /etc/ssh/sshd_config
    regexp: '^(#)?PermitEmptyPasswords '
    line: 'PermitEmptyPasswords no'
  notify: restart sshd
  when:
    - debian9cis_rule_5_2_11
  tags:
    - level1
    - scored
    - patch
    - sshd
    - rule_5.2.11

- name: "SCORED | 5.2.12 | PATCH | Ensure SSH PermitUserEnvironment is disabled"
  lineinfile:
    state: present
    path: /etc/ssh/sshd_config
    regexp: '^(#)?PermitUserEnvironment '
    line: 'PermitUserEnvironment no'
  notify: restart sshd
  when:
    - debian9cis_rule_5_2_12
  tags:
    - level1
    - scored
    - patch
    - sshd
    - rule_5.2.12

- name: "SCORED | 5.2.13 | PATCH | Ensure only strong ciphers are used"
  lineinfile:
    state: present
    path: /etc/ssh/sshd_config
    regexp: '^(#)?Ciphers '
    line: "Ciphers {{ debian9cis_sshd['ciphers'] }}"
  notify: restart sshd
  when:
    - debian9cis_rule_5_2_13
  tags:
    - level1
    - scored
    - patch
    - sshd
    - rule_5.2.13

- name: "SCORED | 5.2.14 | PATCH | Ensure only strong MAC algorithms are used"
  lineinfile:
    state: present
    path: /etc/ssh/sshd_config
    regexp: '^(#)?MACs '
    line: "MACs {{ debian9cis_sshd['macs'] }}"
  notify: restart sshd
  when:
    - debian9cis_rule_5_2_14
  tags:
    - level1
    - scored
    - patch
    - sshd
    - rule_5.2.14

- name: "SCORED | 5.2.15 | PATCH | Ensure only strong Key Exchange algorithms are used"
  lineinfile:
    state: present
    path: /etc/ssh/sshd_config
    regexp: '^(#)?KexAlgorithms '
    line: "KexAlgorithms {{ debian9cis_sshd['kexs'] }}"
  notify: restart sshd
  when:
    - debian9cis_rule_5_2_15
  tags:
    - level1
    - scored
    - patch
    - sshd
    - rule_5.2.15

- name: "SCORED | 5.2.16 | PATCH | Ensure SSH Idle Timeout Interval is configured"
  block:
    lineinfile:
      state: present
      path: /etc/ssh/sshd_config
      regexp: '^(#)?ClientAliveInterval '
      line: "ClientAliveInterval {{ debian9cis_sshd['client_alive_interval'] }}"
    lineinfile:
      state: present
      path: /etc/ssh/sshd_config
      regexp: '^(#)?ClientAliveCountMax '
      line: "ClientAliveCountMax {{ debian9cis_sshd['client_alive_count_max'] }}"
  notify: restart sshd
  when:
    - debian9cis_rule_5_2_16
  tags:
    - level1
    - scored
    - patch
    - sshd
    - rule_5.2.16

- name: "SCORED | 5.2.17 | PATCH | Ensure SSH LoginGraceTime is set to one minute or less"
  lineinfile:
    state: present
    path: /etc/ssh/sshd_config
    regexp: '^(#)?LoginGraceTime '
    line: "LoginGraceTime {{ debian9cis_sshd['login_grace_time'] }}"
  notify: restart sshd
  when:
    - debian9cis_rule_5_2_17
  tags:
    - level1
    - scored
    - patch
    - sshd
    - rule_5.2.17

- name: "SCORED | 5.2.18 | PATCH | Ensure SSH access is limited"
  block:
    - lineinfile:
        state: present
        path: /etc/ssh/sshd_config
        regexp: '^(#)?AllowUsers '
        line: "AllowUsers {{ debian9cis_sshd['allow_users'] }}"
      notify: restart sshd
      when:
        - "{{ debian9cis_sshd['allow_users'] | default('') }}"
    - lineinfile:
        state: present
        path: /etc/ssh/sshd_config
        regexp: '^(#)?AllowGroups '
        line: "AllowGroups {{ debian9cis_sshd['allow_groups'] }}"
      notify: restart sshd
      when:
        - "{{ debian9cis_sshd['allow_groups'] | default('') }}"
    - lineinfile:
        state: present
        path: /etc/ssh/sshd_config
        regexp: '^(#)?DenyUsers '
        line: "DenyUsers {{ debian9cis_sshd['deny_users'] }}"
      notify: restart sshd
      when:
        - "{{ debian9cis_sshd['deny_users'] | default('') }}"
    - lineinfile:
        state: present
        path: /etc/ssh/sshd_config
        regexp: '^(#)?DenyGroups '
        line: "DenyGroups {{ debian9cis_sshd['deny_groups'] }}"
      notify: restart sshd
      when:
        - "{{ debian9cis_sshd['deny_groups'] | default('') }}"
  when:
    - debian9cis_rule_5_2_18
  tags:
    - level1
    - scored
    - patch
    - sshd
    - rule_5.2.18
    - notimplemented

- name: "SCORED | 5.2.19 | PATCH | Ensure SSH warning banner is configured"
  lineinfile:
    state: present
    path: /etc/ssh/sshd_config
    regexp: '^(#)?Banner '
    line: "Banner /etc/issue.net"
  notify: restart sshd
  when:
    - debian9cis_rule_5_2_19
  tags:
    - level1
    - scored
    - patch
    - sshd
    - rule_5.2.19

# ----------------------------------------------------------------------
# Section 5.3
# Configure PAM
# ----------------------------------------------------------------------

- name: "SCORED | 5.3.1 | PATCH | Ensure password creation requirements are configured"
  block:
    - apt:
        name: libpam-pwquality
        state: present
        install_recommends: no
    - lineinfile:
        state: present
        path: /etc/security/pwquality.conf
        regexp: '^{{ item.key }} = '
        line: '{{ item.key }} = {{ item.value }}'
      with_items:
        - "{{ debian9cis_pwquality }}"
    - lineinfile:
        state: present
        path: /etc/pam.d/common-password
        regexp: '^password requisite pam_pwquality'
        line: 'password requisite pam_pwquality.so retry=3'
  when:
    - debian9cis_rule_5_3_1
  tags:
    - level1
    - scored
    - patch
    - rule_5.3.1

- name: "SCORED | 5.3.2 | PATCH | Ensure lockout for failed password attempts is configured"
  lineinfile:
    path: /etc/pam.d/common-auth
    state: present
    regexp: '^auth required pam_tally2'
    line: 'auth required pam_tally2.so onerr=fail audit silent deny=5 unlock_time=900'
  when:
    - debian9cis_rule_5_3_2
  tags:
    - level1
    - scored
    - patch
    - rule_5.3.2

- name: "SCORED | 5.3.3 | PATCH | Ensure password reuse is limited"
  lineinfile:
    path: /etc/pam.d/common-password
    state: present
    regexp: '^password required pam_pwhistory'
    line: 'password required pam_pwhistory.so remember=5'
  when:
    - debian9cis_rule_5_3_3
  tags:
    - level1
    - scored
    - patch
    - rule_5.3.3

- name: "SCORED | 5.3.4 | PATCH | Ensure password hashing algorithm is SHA-512"
  lineinfile:
    path: /etc/pam.d/common-password
    state: present
    regexp: '^password\s+((\S+\s+)+)pam_unix\.so\s+(.*)(md5|sha512)(.*)$'
    line: 'password \1pam_unix.so \2sha512\4'
    #regexp: '^password\s+(\S+\s+)+pam_unix'
    #line: 'password [success=1 default=ignore] pam_unix.so obscure sha512'
  when:
    - debian9cis_rule_5_3_4
  tags:
    - level1
    - scored
    - patch
    - rule_5.3.4

# ----------------------------------------------------------------------
# Section 5.4
# User Accounts and Environment
# ----------------------------------------------------------------------

# ----------------------------------------------------------------------
# Section 5.5
# root login
# ----------------------------------------------------------------------

# ----------------------------------------------------------------------
# Section 5.6
# su access
# ----------------------------------------------------------------------

# End -- Section 5
# ======================================================================
