---
# file: tasks/section_4.yml
# ======================================================================
# Section 4
# Logging and Auditing
# ======================================================================

# ----------------------------------------------------------------------
# Section 4.1
# Configure System Accounting (auditd)
# ----------------------------------------------------------------------

# ----------------------------------------------------------------------
# Section 4.2
# Configure Logging
# ----------------------------------------------------------------------

# ----------------------------------------------------------------------
# Section 4.3
# Logrotate
# ----------------------------------------------------------------------

- name: "NOTSCORED | 4.3 | PATCH | Ensure logrotate is configured"
  debug: msg=TODO
  tags:
    - level1
    - notscored
    - patch
    - logrotate
    - rule_4.3

# End -- Section 4
# ======================================================================
